/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_section;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author tjite
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    
    
    public login() {
        initComponents();
        
        //center the from
        this.setLocationRelativeTo(null);
        
        //create a black border for the exit label
        Border jLabel_exit_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        //set the border to the exit label
        jLabel_exit.setBorder(jLabel_exit_border);
        
        jbuttlogin.setBackground(Color.blue);
        jbuttlogin.setForeground(Color.white);
        jbuttexit.setBackground(Color.blue);
        jbuttexit.setForeground(Color.white);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jtxtusername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbuttlogin = new javax.swing.JButton();
        jbuttexit = new javax.swing.JButton();
        jtxtpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel_exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_exit.setText("  X ");
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("SuperMarket Billing System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jtxtusername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtusernameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        jbuttlogin.setBackground(new java.awt.Color(0, 84, 140));
        jbuttlogin.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jbuttlogin.setForeground(new java.awt.Color(0, 0, 204));
        jbuttlogin.setText("Log In");
        jbuttlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttloginActionPerformed(evt);
            }
        });
        jbuttlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbuttloginKeyPressed(evt);
            }
        });

        jbuttexit.setBackground(new java.awt.Color(0, 84, 140));
        jbuttexit.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jbuttexit.setForeground(new java.awt.Color(0, 0, 204));
        jbuttexit.setText("Exit");
        jbuttexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttexitActionPerformed(evt);
            }
        });

        jtxtpassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpasswordActionPerformed(evt);
            }
        });
        jtxtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtpasswordKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 102, 0));
        jLabel3.setText("LOG IN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jbuttlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbuttexit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel3)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttlogin)
                    .addComponent(jbuttexit))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtusernameActionPerformed

    private void jbuttloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttloginActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/market","root","");
            Statement st= con.createStatement();
           
            ResultSet rs;
            
            // get the username & password
            String username = jtxtusername.getText();
            String password = String.valueOf(jtxtpassword.getPassword());
        
            //create a select query to check if the username and the password exist in the database
            String query = "SELECT * FROM users WHERE username ='"+username+"' AND password = '"+password+"'";
            
            // show a message if the username or the password fields are empty
            if(username.trim().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter Your Username", "Empty Username", 2);
                jtxtusername.requestFocus();
            }
            else if(password.trim().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty Password", 2);
                jtxtpassword.requestFocus();
            }
            else{
                
                try {
                    rs = st.executeQuery(query);
                    if(rs.next())
                    {
                        String user_type=rs.getString("type");
                        int status=rs.getInt("status");
                        //System.out.println(user_type);
                        // show a new form
                        if(status==1){
                                if(user_type.equals("admin")){
                                Menu_Form_admin forma = new Menu_Form_admin(username);
                                forma.setVisible(true);
                                forma.pack();
                                forma.setLocationRelativeTo(null);
                                // close the current form(login form)
                                this.dispose();
                                }
                                else if(user_type.equals("cashier")&&(status==1)){
                                Menu_Form_cashier formc = new Menu_Form_cashier(username);
                                formc.setVisible(true);
                                formc.pack();
                                formc.setLocationRelativeTo(null);
                                // close the current form(login form)
                                this.dispose();

                                }
                        }else{
                             JOptionPane.showMessageDialog(null, "Contact administrator","Login Error",2);
                             jtxtpassword.setText("");
                            jtxtusername.setText("");
                            jtxtusername.requestFocus();
                        }
                        
                    }else{
                        // error message
                        JOptionPane.showMessageDialog(null, "Invalid Username / Password","Login Error",2);
                        jtxtpassword.setText("");
                        jtxtusername.setText("");
                        jtxtusername.requestFocus();
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        
        st.close();
        con.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jbuttloginActionPerformed

    private void jtxtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpasswordActionPerformed

    private void jbuttexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbuttexitActionPerformed

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jLabel_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseEntered
        // TODO add your handling code here:
        
        //create a black border for the exit label
        Border jLabel_exit_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        //set the border to the exit label
        jLabel_exit.setBorder(jLabel_exit_border);
    }//GEN-LAST:event_jLabel_exitMouseEntered

    private void jLabel_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseExited
        // TODO add your handling code here:
        
        //create a black border for the exit label
        Border jLabel_exit_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        //set the border to the exit label
        jLabel_exit.setBorder(jLabel_exit_border);
    }//GEN-LAST:event_jLabel_exitMouseExited

    private void jbuttloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbuttloginKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/market","root","");
            Statement st= con.createStatement();
           
            ResultSet rs;
            
            // get the username & password
            String username = jtxtusername.getText();
            String password = String.valueOf(jtxtpassword.getPassword());
        
            //create a select query to check if the username and the password exist in the database
            String query = "SELECT * FROM users WHERE username ='"+username+"' AND password = '"+password+"'";
            
            // show a message if the username or the password fields are empty
            if(username.trim().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter Your Username", "Empty Username", 2);
                jtxtusername.requestFocus();
            }
            else if(password.trim().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty Password", 2);
                jtxtpassword.requestFocus();
            }
            else{
                
                try {
                    rs = st.executeQuery(query);
                    if(rs.next())
                    {
                        String user_type=rs.getString("type");
                        int status=rs.getInt("status");
                        //System.out.println(user_type);
                        // show a new form
                        if(status==1){
                                if(user_type.equals("admin")){
                                Menu_Form_admin forma = new Menu_Form_admin(username);
                                forma.setVisible(true);
                                forma.pack();
                                forma.setLocationRelativeTo(null);
                                // close the current form(login form)
                                this.dispose();
                                }
                                else if(user_type.equals("cashier")&&(status==1)){
                                Menu_Form_cashier formc = new Menu_Form_cashier(username);
                                formc.setVisible(true);
                                formc.pack();
                                formc.setLocationRelativeTo(null);
                                // close the current form(login form)
                                this.dispose();

                                }
                        }else{
                             JOptionPane.showMessageDialog(null, "Contact administrator","Login Error",2);
                             jtxtpassword.setText("");
                            jtxtusername.setText("");
                            jtxtusername.requestFocus();
                        }
                        
                    }else{
                        // error message
                        JOptionPane.showMessageDialog(null, "Invalid Username / Password","Login Error",2);
                        jtxtpassword.setText("");
                        jtxtusername.setText("");
                        jtxtusername.requestFocus();
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
           
        st.close();
        con.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
    }//GEN-LAST:event_jbuttloginKeyPressed

    private void jtxtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/market","root","");
            Statement st= con.createStatement();
           
            ResultSet rs;
            
            // get the username & password
            String username = jtxtusername.getText();
            String password = String.valueOf(jtxtpassword.getPassword());
        
            //create a select query to check if the username and the password exist in the database
            String query = "SELECT * FROM users WHERE username ='"+username+"' AND password = '"+password+"'";
            
            // show a message if the username or the password fields are empty
            if(username.trim().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter Your Username", "Empty Username", 2);
                jtxtusername.requestFocus();
            }
            else if(password.trim().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty Password", 2);
                jtxtpassword.requestFocus();
            }
            else{
                
                try {
                    rs = st.executeQuery(query);
                    if(rs.next())
                    {
                        String user_type=rs.getString("type");
                        int status=rs.getInt("status");
                        //System.out.println(user_type);
                        // show a new form
                        if(status==1){
                                if(user_type.equals("admin")){
                                Menu_Form_admin forma = new Menu_Form_admin(username);
                                forma.setVisible(true);
                                forma.pack();
                                forma.setLocationRelativeTo(null);
                                // close the current form(login form)
                                this.dispose();
                                }
                                else if(user_type.equals("cashier")&&(status==1)){
                                Menu_Form_cashier formc = new Menu_Form_cashier(username);
                                formc.setVisible(true);
                                formc.pack();
                                formc.setLocationRelativeTo(null);
                                // close the current form(login form)
                                this.dispose();

                                }
                        }else{
                             JOptionPane.showMessageDialog(null, "Contact administrator","Login Error",2);
                             jtxtpassword.setText("");
                            jtxtusername.setText("");
                            jtxtusername.requestFocus();
                        }
                        
                    }else{
                        // error message
                        JOptionPane.showMessageDialog(null, "Invalid Username / Password","Login Error",2);
                        jtxtpassword.setText("");
                        jtxtusername.setText("");
                        jtxtusername.requestFocus();
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
             st.close();
        con.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
    }//GEN-LAST:event_jtxtpasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbuttexit;
    private javax.swing.JButton jbuttlogin;
    private javax.swing.JPasswordField jtxtpassword;
    private javax.swing.JTextField jtxtusername;
    // End of variables declaration//GEN-END:variables
}
